# Generated by Django 5.2.17 on 2026-09-23 06:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.SlugField(max_length=80, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=120, verbose_name='设备名称')),
                ('vehicle_plate', models.CharField(blank=True, max_length=32, verbose_name='车牌号')),
                ('enabled', models.BooleanField(default=True, verbose_name='允许接入')),
                ('api_key_hash', models.CharField(blank=True, editable=False, max_length=256, verbose_name='设备密钥摘要')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('last_seen', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最近上报时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='事件编号')),
                ('event_type', models.CharField(choices=[('eye_closure', '持续闭眼'), ('yawn', '打哈欠'), ('head_down', '低头'), ('look_away', '视线偏离'), ('phone_use', '使用手机'), ('smoking', '吸烟'), ('drinking', '喝水'), ('hand_anomaly', '手部异常')], max_length=24, verbose_name='行为类型')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='接收时间')),
                ('severity', models.CharField(choices=[('warning', '警告'), ('critical', '严重')], default='warning', max_length=16, verbose_name='等级')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='持续时长（毫秒）')),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='置信度')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='补充信息')),
                ('evidence', models.FileField(blank=True, upload_to=events.models.evidence_upload_path, verbose_name='证据图片')),
                ('evidence_sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='证据摘要')),
                ('payload_hash', models.CharField(editable=False, max_length=64, verbose_name='请求摘要')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '报警事件',
                'verbose_name_plural': '报警事件',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['device', '-occurred_at'], name='event_device_time_idx'), models.Index(fields=['event_type', '-occurred_at'], name='event_type_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='event_confidence_range'), models.CheckConstraint(condition=models.Q(('event_type__in', ['eye_closure', 'yawn', 'head_down', 'look_away', 'phone_use', 'smoking', 'drinking', 'hand_anomaly'])), name='event_type_valid'), models.CheckConstraint(condition=models.Q(('severity__in', ['warning', 'critical'])), name='event_severity_valid')],
            },
        ),
    ]
